#!/usr/bin/env bash

ANS=$(echo "   Power-openbox|   Power-i3|   Switch-window|  Programs|   Find-files|  Find-icon| " | \
                rofi -sep "|" -dmenu -i -p 'System: ' "" -width 25 \
                -hide-scrollbar -eh 1 -line-padding 5 -padding 25 -columns 1 -lines 6)
            case "$ANS" in
                *Power-openbox) ~/.config/rofi/rofi-sh -l ;;
                *Power-i3) ~/.config/rofi/rofi-sh -s ;;
                *Switch-window) ~/.config/rofi/rofi-sh -w ;;
                *Programs) ~/.config/rofi/rofi-sh -r ;;
                *Find-files) ~/.config/rofi/rofi-sh -f ;;
                *Find-icon) ~/.config/rofi/rofi-sh -i
            esac


exit 0

