#!/bin/bash

options='-columns 6 -width 100 -lines 20 -bw 2 -yoffset -2 -location 1'

selected=$(\
  cat /home/yahia/.config/rofi/rofi-fontawesome/key-help.txt \
    | rofi -dmenu -i -markup-rows \
    ${options}
    )

# exit if nothing is selected
[[ -z $selected ]] && exit

echo -ne $(echo "$selected" |\
  awk -F';' -v RS='>' '
    NR==2{sub("&#x","",$1);print "\\u" $1;exit}'
) |  xclip -selection clipboard && xdotool key ctrl+shift+v



