#!/bin/bash

ROOT="$(readlink -f $(dirname "$0"))"
mkdir -p ./.config

rsync -r  -t  --info=progress2 --delete -l -s $HOME/.config/i3  ./.config

rsync -r  -t  --info=progress2 --delete -l -s $HOME/.config/rofi ./.config

rsync -r  -t  --info=progress2 --delete -l -s $HOME/.config/scripts  ./.config
