#!/bin/bash
cd  "$(readlink -f $(dirname "$0"))"
  ANS=$(echo "...Back|  BooksOrg| Adhan| AbiWord| Kwrite" | \
                rofi -sep "|" -dmenu -i -p 'Office ' "" -width 20 \
                -hide-scrollbar -eh 1 -line-padding 5 -padding 20 -columns 1 -lines 7)
           
            case "$ANS" in
                *...Back)   ./rofi-mainmenu ;;
                *BooksOrg)  booksorg ;;
                *Adhan)     elokab-adhan ;;
                *AbiWord)   abiword ;;
                *Kwrite)    kwrite
            esac 
           
exit 0
